# Replace the text below to customize your site
site_name: Cagsun Acemoglu - MDEF & Fab Lab Barcelona
site_description: Master in Design for Emergent Futures
site_author: Cagsun Acemoglu
copyright: Copyleft 2021 "Cagsun Acemoglu" - GNU Free Documentation License
repo_name: 'Name : Github Repo'
site_url: https://cagsunacemoglu.github.io/MDEF/
repo_url: 'https://github.com/cagsunacemoglu/MDEF'


nav:
  - Home: index.md
  - About: about/me.md
  - Seminars :
      - Term 1:
          - Bootcamp: term1/01-Bootcamp.md
          - Design Studio: 
            - Roles of Prototyping: term1/03-Roles of Prototyping.md
            - Communication Strategy: term1/Communication.md
          - AoWS: term1/02-Atlas of Weak Signals.md  
          - Bio & Agri: term1/04-Bio Agri Zero.md
          - Living with Your Own Ideas: term1/05-Living with Your Own Ideas.md
          - Tech Beyond the Myth: term1/06-Tech Beyond the Myth.md
          - Community Engagement: term1/06-Community Engagement.md
          - Extended Intelligences: term1/07-Extended Intelligences.md
      - Term 2:
          - Design Studio: 
            - Reframing of my project: term2/DS/01-Reframing of my project.md
          - Designing for the Next Billion Seconds: term2/01-Designing for the next billion seconds.md
          - Remixing Materials: term2/02-Remixing Materials.md
          - Digital Prototyping:
            - Electronics & Coding: term2/FABLAB/01-ElectronicsCoding.md
            - Design Tools: term2/FABLAB/03-Algorithmic Design.md
            - 2D Fabrication: term2/FABLAB/02-2DFabrication.md
            - Inputs & Outputs: term2/FABLAB/04-Inputs & Outputs.md
            - /// Challenge I: term2/MicroChallenge I.md
            - Networking: term2/FABLAB/05-Networking.md
            - 3D Fabrication & Scanning: term2/FABLAB/06-3D.md
            - Interfaces - Machine Interactions: term2/FABLAB/07-Interfaces.md
            - CNC: term2/FABLAB/08-CNC.md
            - /// Challenge II: term2/MicroChallenge II.md
          - Making Sense and Meaning: term2/03-MakingSense.md
          - Communicating Ideas: term2/04-CommunicatingIdeas.md
          - Measuring the World: term2/05-MeasuringTheWorld.md
          - Research Trip: term2/elHierro.md
      - Term 3:
          - Design Studio: 
            - Role in Alternative Presents: term3/myRole.md
          - Distributed Design: term3/DistDesign.md
          - Digital Prototyping:
            - Robots: term3/FABLAB/robots.md
            - Blender: term3/FABLAB/blender.md
            - Live Coding: term3/FABLAB/liveCoding.md
          - Design Ethics: term3/ethics.md
  - Master project:
      - Initial ideas: project/project.md
      # - Term 2:
      #     - digi: term1/01-Bootcamp.md
      #     - studio: term1/01-Bootcamp.md




extra:
  social:
    # For other social icons at https://squidfunk.github.io/mkdocs-material/setup/adding-social-links/
    - icon: fontawesome/brands/medium
      link: https://medium.com/
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/
    - icon: fontawesome/brands/linkedin
      link: "https://www.linkedin.com/in/"
    - icon: fontawesome/brands/github
      link: "https://github.com/"

theme:
  name: material
  palette:
    # try other colors https://squidfunk.github.io/mkdocs-material/getting-started/#primary-colors
    primary: yellow
    accent: purple
  font:
    # See available fonts at https://fonts.google.com/
    text: Be Vietnam
    code: Cutive Mono
  icon:
    logo: material/memory
  favicon: images/favicon.svg
  features:
    - instant
    - navigation.expand
    - navigation.indexes
    - navigation.instant
    # - navigation.prune
    # - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking

plugins:
  - search
  - git-revision-date-localized:
      fallback_to_build_date: true

markdown_extensions:
  - extra
  - smarty
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

  - md_in_html
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      base_path: 'docs'
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - attr_list
  - pymdownx.tabbed

extra_css:
  - stylesheets/extra.css
  - https://unpkg.com/material-components-web@latest/dist/material-components-web.min.css
